version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5437:5432"  # Expondo a porta do banco para conexão local

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
