pipeline {
    agent any

    stages {
        stage('SCM Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Franck-Patrick/Desafio_DellTech.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -f Demanda3/Dockerfile -t pkdu14/webapp:$BUILD_NUMBER .'
            }
        }
    }
}